import { db } from '@/db';
import { loanApplications } from '@/db/schema';

async function main() {
    const sampleLoanApplications = [
        {
            name: 'Rajesh Kumar Sharma',
            phone: '9876543210',
            email: 'rajesh.sharma@techcorp.com',
            city: 'Delhi',
            loanType: 'home',
            amount: 3500000,
            monthlyIncome: 85000,
            consent: true,
            status: 'pending',
            createdAt: new Date('2024-12-15T10:30:00Z').toISOString(),
            updatedAt: new Date('2024-12-15T10:30:00Z').toISOString(),
        },
        {
            name: 'Priya Mehta',
            phone: '8765432109',
            email: 'priya.mehta@infotech.in',
            city: 'Mumbai',
            loanType: 'business',
            amount: 1200000,
            monthlyIncome: 65000,
            consent: true,
            status: 'approved',
            createdAt: new Date('2024-12-12T14:15:00Z').toISOString(),
            updatedAt: new Date('2024-12-18T09:20:00Z').toISOString(),
        },
        {
            name: 'Arjun Patel',
            phone: '7654321098',
            email: 'arjun.patel@student.gmail.com',
            city: 'Ahmedabad',
            loanType: 'education',
            amount: 450000,
            monthlyIncome: 25000,
            consent: true,
            status: 'pending',
            createdAt: new Date('2024-12-10T16:45:00Z').toISOString(),
            updatedAt: new Date('2024-12-10T16:45:00Z').toISOString(),
        },
        {
            name: 'Sunita Reddy',
            phone: '9123456789',
            email: 'sunita.reddy@pharma.co.in',
            city: 'Hyderabad',
            loanType: 'personal',
            amount: 280000,
            monthlyIncome: 42000,
            consent: true,
            status: 'pending',
            createdAt: new Date('2024-12-08T11:20:00Z').toISOString(),
            updatedAt: new Date('2024-12-08T11:20:00Z').toISOString(),
        },
        {
            name: 'Vikram Singh',
            phone: '8234567890',
            email: 'vikram.singh@manufacturing.com',
            city: 'Pune',
            loanType: 'home',
            amount: 4200000,
            monthlyIncome: 95000,
            consent: true,
            status: 'approved',
            createdAt: new Date('2024-12-05T13:30:00Z').toISOString(),
            updatedAt: new Date('2024-12-20T15:45:00Z').toISOString(),
        },
        {
            name: 'Kavitha Nair',
            phone: '7345678901',
            email: 'kavitha.nair@itservices.in',
            city: 'Bangalore',
            loanType: 'business',
            amount: 800000,
            monthlyIncome: 55000,
            consent: true,
            status: 'pending',
            createdAt: new Date('2024-12-03T09:15:00Z').toISOString(),
            updatedAt: new Date('2024-12-03T09:15:00Z').toISOString(),
        },
        {
            name: 'Amit Gupta',
            phone: '6456789012',
            email: 'amit.gupta@finance.org',
            city: 'Chennai',
            loanType: 'education',
            amount: 650000,
            monthlyIncome: 38000,
            consent: true,
            status: 'rejected',
            createdAt: new Date('2024-12-01T12:00:00Z').toISOString(),
            updatedAt: new Date('2024-12-07T10:30:00Z').toISOString(),
        },
        {
            name: 'Deepika Chatterjee',
            phone: '9567890123',
            email: 'deepika.chatterjee@consulting.com',
            city: 'Kolkata',
            loanType: 'personal',
            amount: 150000,
            monthlyIncome: 32000,
            consent: true,
            status: 'pending',
            createdAt: new Date('2024-11-28T14:45:00Z').toISOString(),
            updatedAt: new Date('2024-11-28T14:45:00Z').toISOString(),
        },
        {
            name: 'Rohit Agarwal',
            phone: '8678901234',
            email: 'rohit.agarwal@textiles.co.in',
            city: 'Mumbai',
            loanType: 'business',
            amount: 1800000,
            monthlyIncome: 78000,
            consent: true,
            status: 'pending',
            createdAt: new Date('2024-11-26T08:30:00Z').toISOString(),
            updatedAt: new Date('2024-11-26T08:30:00Z').toISOString(),
        },
        {
            name: 'Ananya Iyer',
            phone: '7789012345',
            email: 'ananya.iyer@research.edu.in',
            city: 'Bangalore',
            loanType: 'education',
            amount: 320000,
            monthlyIncome: 28000,
            consent: true,
            status: 'approved',
            createdAt: new Date('2024-11-25T17:20:00Z').toISOString(),
            updatedAt: new Date('2024-12-16T11:15:00Z').toISOString(),
        }
    ];

    await db.insert(loanApplications).values(sampleLoanApplications);
    
    console.log('✅ Loan applications seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});