import { db } from '@/db';
import { loanDocs } from '@/db/schema';

async function main() {
    const sampleLoanDocs = [
        // Home Loan Documents
        {
            loanType: 'home',
            documentName: 'Aadhar Card',
            description: 'Government issued identity proof with valid address',
            isMandatory: true,
            iconName: 'CreditCard',
            displayOrder: 1,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            loanType: 'home',
            documentName: 'PAN Card',
            description: 'Permanent Account Number for income tax purposes',
            isMandatory: true,
            iconName: 'FileText',
            displayOrder: 2,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            loanType: 'home',
            documentName: 'Salary Slips (Last 3 months)',
            description: 'Latest salary certificates from employer',
            isMandatory: true,
            iconName: 'Receipt',
            displayOrder: 3,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            loanType: 'home',
            documentName: 'Bank Statements (Last 6 months)',
            description: 'Salary account bank statements showing regular credit',
            isMandatory: true,
            iconName: 'Landmark',
            displayOrder: 4,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            loanType: 'home',
            documentName: 'Property Documents',
            description: 'Sale deed, title documents, and property papers',
            isMandatory: true,
            iconName: 'Building',
            displayOrder: 5,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            loanType: 'home',
            documentName: 'NOC from Employer',
            description: 'No Objection Certificate from current employer',
            isMandatory: false,
            iconName: 'FileCheck',
            displayOrder: 6,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },

        // Business Loan Documents
        {
            loanType: 'business',
            documentName: 'Business Registration Certificate',
            description: 'Certificate of incorporation or partnership deed',
            isMandatory: true,
            iconName: 'Building2',
            displayOrder: 1,
            createdAt: new Date('2024-01-11').toISOString(),
            updatedAt: new Date('2024-01-11').toISOString(),
        },
        {
            loanType: 'business',
            documentName: 'GST Registration Certificate',
            description: 'Valid GST registration and compliance certificates',
            isMandatory: true,
            iconName: 'Receipt',
            displayOrder: 2,
            createdAt: new Date('2024-01-11').toISOString(),
            updatedAt: new Date('2024-01-11').toISOString(),
        },
        {
            loanType: 'business',
            documentName: 'ITR (Last 3 years)',
            description: 'Income Tax Returns of business for last 3 financial years',
            isMandatory: true,
            iconName: 'FileText',
            displayOrder: 3,
            createdAt: new Date('2024-01-11').toISOString(),
            updatedAt: new Date('2024-01-11').toISOString(),
        },
        {
            loanType: 'business',
            documentName: 'Business Bank Statements',
            description: 'Current account statements for last 12 months',
            isMandatory: true,
            iconName: 'Landmark',
            displayOrder: 4,
            createdAt: new Date('2024-01-11').toISOString(),
            updatedAt: new Date('2024-01-11').toISOString(),
        },
        {
            loanType: 'business',
            documentName: 'Financial Statements',
            description: 'Audited balance sheet and profit & loss statements',
            isMandatory: true,
            iconName: 'Calculator',
            displayOrder: 5,
            createdAt: new Date('2024-01-11').toISOString(),
            updatedAt: new Date('2024-01-11').toISOString(),
        },
        {
            loanType: 'business',
            documentName: 'Project Report',
            description: 'Detailed business plan and project feasibility report',
            isMandatory: false,
            iconName: 'FileBarChart',
            displayOrder: 6,
            createdAt: new Date('2024-01-11').toISOString(),
            updatedAt: new Date('2024-01-11').toISOString(),
        },

        // Education Loan Documents
        {
            loanType: 'education',
            documentName: 'Admission Letter',
            description: 'Official admission confirmation from educational institution',
            isMandatory: true,
            iconName: 'GraduationCap',
            displayOrder: 1,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            loanType: 'education',
            documentName: 'Fee Structure',
            description: 'Complete fee breakdown and payment schedule from institute',
            isMandatory: true,
            iconName: 'Receipt',
            displayOrder: 2,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            loanType: 'education',
            documentName: 'Student ID Proof',
            description: 'Aadhar card or passport of student',
            isMandatory: true,
            iconName: 'CreditCard',
            displayOrder: 3,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            loanType: 'education',
            documentName: 'Guarantor Income Proof',
            description: 'Salary slips and ITR of co-applicant or guarantor',
            isMandatory: true,
            iconName: 'User',
            displayOrder: 4,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            loanType: 'education',
            documentName: 'Academic Records',
            description: 'Mark sheets and certificates of previous qualifications',
            isMandatory: true,
            iconName: 'FileText',
            displayOrder: 5,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            loanType: 'education',
            documentName: 'Scholarship Certificate',
            description: 'Documents proving scholarship or financial aid received',
            isMandatory: false,
            iconName: 'Award',
            displayOrder: 6,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },

        // Personal Loan Documents
        {
            loanType: 'personal',
            documentName: 'Photo ID Proof',
            description: 'Aadhar card, driving license, or passport',
            isMandatory: true,
            iconName: 'CreditCard',
            displayOrder: 1,
            createdAt: new Date('2024-01-13').toISOString(),
            updatedAt: new Date('2024-01-13').toISOString(),
        },
        {
            loanType: 'personal',
            documentName: 'Address Proof',
            description: 'Utility bill, rental agreement, or address proof',
            isMandatory: true,
            iconName: 'MapPin',
            displayOrder: 2,
            createdAt: new Date('2024-01-13').toISOString(),
            updatedAt: new Date('2024-01-13').toISOString(),
        },
        {
            loanType: 'personal',
            documentName: 'Salary Slips (Last 3 months)',
            description: 'Recent salary certificates from current employer',
            isMandatory: true,
            iconName: 'Receipt',
            displayOrder: 3,
            createdAt: new Date('2024-01-13').toISOString(),
            updatedAt: new Date('2024-01-13').toISOString(),
        },
        {
            loanType: 'personal',
            documentName: 'Bank Statements (Last 6 months)',
            description: 'Salary account statements showing regular income',
            isMandatory: true,
            iconName: 'Landmark',
            displayOrder: 4,
            createdAt: new Date('2024-01-13').toISOString(),
            updatedAt: new Date('2024-01-13').toISOString(),
        },
        {
            loanType: 'personal',
            documentName: 'Employment Certificate',
            description: 'Letter from employer confirming employment status',
            isMandatory: true,
            iconName: 'Briefcase',
            displayOrder: 5,
            createdAt: new Date('2024-01-13').toISOString(),
            updatedAt: new Date('2024-01-13').toISOString(),
        },
        {
            loanType: 'personal',
            documentName: 'ITR (Last 2 years)',
            description: 'Income tax returns for additional income verification',
            isMandatory: false,
            iconName: 'FileText',
            displayOrder: 6,
            createdAt: new Date('2024-01-13').toISOString(),
            updatedAt: new Date('2024-01-13').toISOString(),
        },
    ];

    await db.insert(loanDocs).values(sampleLoanDocs);
    
    console.log('✅ Loan documents seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});